services:
  api:
    depends_on:
      - db
    container_name: divain_api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./api:/app
    environment:
      - ENV=development

  db:
    container_name: divain_db
    image: postgres:${POSTGRES_TAG:-latest}
    restart: always
    environment:
      POSTGRES_USER: divain_user
      POSTGRES_PASSWORD: divain_pass
      POSTGRES_DB: divain_db
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U divain_user -d divain_db']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  frontend:
    container_name: divain_frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - '5174:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  db_data: {}
